name: 🚀 Release

on:
  workflow_dispatch:
    inputs:
      environment:
        type: choice
        options:
          - 'uat'
          - 'production'

jobs:
  release:
    runs-on: ubuntu-latest
    steps:
      - name: 💻 Checkout current pull-request revision code
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: 💼 Configure Git user
        run: |
          git config user.name "${GITHUB_ACTOR}"
          git config user.email "${GITHUB_ACTOR}@users.noreply.github.com"
      - name: 📦 Install package dependencies using lockfile
        run: npm ci

      - name: 🚀 Run new version for production
        if: contains(inputs.environment, 'production')
        run: npx release-it --ci
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}

      - name: 🚀 Run new version for uat
        if: contains(inputs.environment, 'uat')
        run: npx release-it --ci --preRelease=uat
        env:
          GITHUB_TOKEN: ${{ secrets.TOKEN }}
      